// End-to-end address derivation test:
//   mnemonic → seed → BIP-32 master → m/86'/808276'/0'/0/i → BIP-86 tweak → prl1p…
//
// This is the most important invariant for the wallet: if derivation
// regresses, restored wallets show the wrong address and funds appear
// "missing". We pin against btcd-oyster (pearl-research-labs/pearl), the
// canonical Pearl L1 reference wallet. Pearl uses HDCoinType = 808276
// (ASCII "PRL"), not the BIP-44 BTC value 0. Vectors below were produced
// by oyster mainnet from the BIP-39 vector 1 seed and the same seed
// through this wallet must reproduce them byte-for-byte.

import { describe, it, expect } from "vitest";
import { HDKey } from "@scure/bip32";
import * as bip39 from "@scure/bip39";
import { wordlist } from "@scure/bip39/wordlists/english";
import {
  pearlAddressFromInternalKey,
  pearlAddressFromCompressedPubkey,
} from "../src/chains/pearl/address";
import { pearlParams } from "../src/chains/pearl/network";
import {
  DEFAULT_PEARL_PATH,
  PEARL_COIN_TYPE,
  RECEIVE_GAP_LIMIT,
  masterFromSeed,
  pearlReceivePath,
} from "../src/crypto/hd";

const params = pearlParams("mainnet");

// BIP-39 vector 1 mnemonic — well-known, used by every taproot/BIP-86 ref.
const BIP86_MNEMONIC =
  "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";

// Captured from btcd-oyster mainnet (PRL HDCoinType 808276) on 2026-05-19
// using `oyster --createfromfile` with the BIP-39 vector 1 seed:
//   seed = bip39.mnemonicToSeed(BIP86_MNEMONIC).toString('hex')
// then `getnewaddress` five times. Path = m/86'/808276'/0'/0/{0..4}.
const OYSTER_MAINNET_ADDRESSES = [
  "prl1pr6yuq8u2r95wjzzgpdy8cpnncpl7l8zgy6x5q0367pnc53s2famqg7pt74",
  "prl1pyx3nlscz8rvsxqhcjtyqt2g5szuk9ss7m5saszu3afwwhvn9zp2sz62rhm",
  "prl1pfrfqcvcmghjc3mpsazm9p9ktttyuewzlfmn40dzkwh0muejgkr3sfx9jwd",
  "prl1prmdvgxfgzmqzq5dj58enw6y7c55wpsfdpr0af7t79x65z6gmms8q4qa93j",
  "prl1pc9xyu484gw5wsnq7hg00733jlcr4ethphyxmavynyl8me0q7ec7q6qu3wx",
];

describe("Pearl HD derivation matches oyster mainnet", () => {
  it("PEARL_COIN_TYPE is 808276 (ASCII 'PRL')", () => {
    expect(PEARL_COIN_TYPE).toBe(808276);
    expect(DEFAULT_PEARL_PATH).toBe("m/86'/808276'/0'/0/0");
  });

  it("derives the first 5 addresses bit-exact against oyster mainnet", async () => {
    const seed = await bip39.mnemonicToSeed(BIP86_MNEMONIC);
    const master = masterFromSeed(seed);
    for (let i = 0; i < OYSTER_MAINNET_ADDRESSES.length; i++) {
      const child = master.derive(`m/86'/${PEARL_COIN_TYPE}'/0'/0/${i}`);
      const xOnly = child.publicKey!.slice(1);
      const addr = pearlAddressFromInternalKey(xOnly, params);
      expect(addr).toBe(OYSTER_MAINNET_ADDRESSES[i]);
    }
  });

  it("compressed-pubkey path matches internal-key path", async () => {
    const seed = await bip39.mnemonicToSeed(BIP86_MNEMONIC);
    const master = masterFromSeed(seed);
    const child = master.derive(DEFAULT_PEARL_PATH);
    const compressed = child.publicKey!;
    const xOnly = compressed.slice(1);
    expect(pearlAddressFromCompressedPubkey(compressed, params))
      .toBe(pearlAddressFromInternalKey(xOnly, params));
  });

  it("uses HMAC key 'Bitcoin seed' (standard BIP-32 master)", async () => {
    // Sanity check: HDKey.fromMasterSeed uses the standard BIP-32 master key.
    // If we ever swap to a custom HMAC key, addresses move and restore breaks.
    const seed = await bip39.mnemonicToSeed(BIP86_MNEMONIC);
    const master = HDKey.fromMasterSeed(seed);
    expect(master.publicKey).toBeTruthy();
    expect(master.chainCode).toBeTruthy();
  });

  it("invalid mnemonic is rejected by bip39", () => {
    expect(bip39.validateMnemonic("not a real mnemonic phrase here please", wordlist)).toBe(false);
  });
});

// Round-trip: a fresh mnemonic generated by us, derived twice, produces
// the same address. Catches any nondeterminism in our derivation
// pipeline (which would silently break restore flow).
describe("Wallet self round-trip", () => {
  it("the same mnemonic always derives the same prl1p address", async () => {
    // 12-word BIP-39 mnemonic, fully valid, generated offline.
    const mn = "legal winner thank year wave sausage worth useful legal winner thank yellow";
    const seed1 = await bip39.mnemonicToSeed(mn);
    const seed2 = await bip39.mnemonicToSeed(mn);
    expect(Buffer.from(seed1).toString("hex")).toBe(Buffer.from(seed2).toString("hex"));
    const m1 = masterFromSeed(seed1);
    const m2 = masterFromSeed(seed2);
    const a1 = pearlAddressFromInternalKey(m1.derive(DEFAULT_PEARL_PATH).publicKey!.slice(1), params);
    const a2 = pearlAddressFromInternalKey(m2.derive(DEFAULT_PEARL_PATH).publicKey!.slice(1), params);
    expect(a1).toBe(a2);
    expect(a1.startsWith("prl1p")).toBe(true);
  });

  it("two different mnemonics produce two different addresses", async () => {
    const a = await bip39.mnemonicToSeed("legal winner thank year wave sausage worth useful legal winner thank yellow");
    const b = await bip39.mnemonicToSeed("abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about");
    const addrA = pearlAddressFromInternalKey(masterFromSeed(a).derive(DEFAULT_PEARL_PATH).publicKey!.slice(1), params);
    const addrB = pearlAddressFromInternalKey(masterFromSeed(b).derive(DEFAULT_PEARL_PATH).publicKey!.slice(1), params);
    expect(addrA).not.toBe(addrB);
  });
});

// btcd-oyster compatibility: confirmed bit-exact in
// "derives the first 5 addresses bit-exact against oyster mainnet"
// above. Wallets created by oyster restore cleanly via mnemonic.

// Multi-address receive pool — Pearl L1 is UTXO so an HD wallet may hold
// balances at any of its derived receive indexes (oyster advances the
// index per `getnewaddress`). We derive RECEIVE_GAP_LIMIT addresses on
// every create/restore/unlock and aggregate balances across all of them.
describe("Pearl receive pool", () => {
  it("RECEIVE_GAP_LIMIT is at least 20 (BIP-44 convention)", () => {
    expect(RECEIVE_GAP_LIMIT).toBeGreaterThanOrEqual(20);
  });

  it("pearlReceivePath rejects bad input", () => {
    expect(() => pearlReceivePath(-1)).toThrow();
    expect(() => pearlReceivePath(1.5)).toThrow();
  });

  it("derives RECEIVE_GAP_LIMIT unique addresses from one seed", async () => {
    const seed = await bip39.mnemonicToSeed(BIP86_MNEMONIC);
    const master = masterFromSeed(seed);
    const addrs: string[] = [];
    for (let i = 0; i < RECEIVE_GAP_LIMIT; i++) {
      const child = master.derive(pearlReceivePath(i));
      addrs.push(pearlAddressFromInternalKey(child.publicKey!.slice(1), params));
    }
    expect(addrs).toHaveLength(RECEIVE_GAP_LIMIT);
    expect(new Set(addrs).size).toBe(RECEIVE_GAP_LIMIT);
    // First five must still match oyster mainnet.
    for (let i = 0; i < OYSTER_MAINNET_ADDRESSES.length; i++) {
      expect(addrs[i]).toBe(OYSTER_MAINNET_ADDRESSES[i]);
    }
  });

  it("pearlReceivePath(0) equals DEFAULT_PEARL_PATH", () => {
    expect(pearlReceivePath(0)).toBe(DEFAULT_PEARL_PATH);
  });
});
